require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'vicinity' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])






  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'vicinityTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'vicinity-tvOS' do
  # Pods for vicinity-tvOS

  target 'vicinity-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
